---
- hosts: win

  tasks:
    - name: Check if trigger already enabled
      win_lineinfile:
        path: "{{ triggers_file }}"
        line: "{{ file_path }},{{ bjg_name }}"
      register: Configured

    - name: Run BJG
      ansible.builtin.debug:
        msg: "BJG {{ bjg_name }} started successfully"
      when: Configured.changed != True