---
- hosts: win
  tasks:
    - win_shell: '\\scd-test-01.bsp.simcorpcloud.com\scd-test\NetRoot\Bin\ScdSvcCtl.exe platform ping'
      register: Platform_Status

    - debug: var=Platform_Status.stdout_lines
      